[package]
name = "tui-grep"
version = "0.1.0"
authors = ["roger <rogerduran@gmail.com>"]
edition = "2018"

[dependencies]
tui = "0.6.2"
regex = "1.3.1"
termion = "1.5.3"
crossbeam-channel = "0.3.9"
fixed-vec-deque = "0.1.8"
cansi = "2.1.0"
